# Generated by Django 4.2.1 on 2023-11-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_name_register_username_alter_register_nid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
