# Generated by Django 4.2.1 on 2023-11-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormroom',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
