# Generated by Django 4.2.1 on 2023-11-28 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_dormroom_bookmarked_by_alter_dormroom_posted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dormroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.register')),
            ],
        ),
    ]
