# Generated by Django 4.2.5 on 2023-11-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='register',
            name='nid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.IntegerField(),
        ),
    ]
