# Generated by Django 4.2.1 on 2023-11-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_register_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormRooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('popularity', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('link', models.URLField()),
            ],
        ),
    ]
