# Generated by Django 4.2.1 on 2023-11-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_dormroom_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormroom',
            name='comments',
        ),
        migrations.AddField(
            model_name='dormroom',
            name='comments',
            field=models.ManyToManyField(blank=True, to='users.comment'),
        ),
    ]
