# Generated by Django 4.2.1 on 2023-12-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_proposalresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalresponse',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
