# Generated by Django 4.2.1 on 2023-11-17 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_dormroom_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormroom',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.comment'),
        ),
    ]
